spring.application.name=OJT

spring.datasource.url=jdbc:mysql://localhost/ojt_bd?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Nguyenthuy92@

spring.jpa.hibernate.ddl-auto=update